import { AUDIENCE, AUTH, page } from "./helpers.mjs";

const sideNav = (label) => ({
  name: `«${label}» في القائمة الجانبية`,
  type: "رابط تنقل",
  description: `ينقلك إلى ${label}. العنصر النشط مميّز بلون الهوية.`,
});

const periodBanner = {
  name: "شريط السنة والفصل الدراسي",
  type: "بانر",
  description: "يعرض الفصل والسنة النشطين — كل العمليات (واجبات، علامات) مرتبطة بهذه الفترة.",
};

export const teacherPages = [
  page({
    id: "teacher-home",
    section: "بوابة المعلم",
    title: "فصولي",
    path: "/teacher",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "عرض الفصول والشعب المسندة للمعلم.",
    overview: "بطاقات لكل شعبة: اسم الصف، عدد الطلاب، وزر للدخول لتفاصيل الفصل.",
    elements: [
      sideNav("فصولي"),
      sideNav("جدول حصصي"),
      sideNav("الواجبات"),
      sideNav("الاختبارات"),
      sideNav("إضافة التقييمات والعلامات للطلاب"),
      sideNav("الإعلانات"),
      sideNav("مرفقات المواد"),
      sideNav("أرشيف السنوات السابقة"),
      sideNav("سيرتي الذاتية"),
      periodBanner,
      {
        name: "بطاقة شعبة",
        type: "بطاقة",
        description: "اسم الشعبة (مثل: الصف الأول - أ). الضغط يفتح /teacher/classes/[id] بقائمة الطلاب.",
      },
    ],
    subPages: [
      {
        path: "/teacher/classes/[id]",
        title: "تفاصيل شعبة",
        description: "جدول طلاب الشعبة مع أرقامهم. نقطة انطلاق لإدخال العلامات أو متابعة الواجبات.",
      },
    ],
  }),
  page({
    id: "teacher-schedules",
    section: "بوابة المعلم",
    title: "جدول حصصي",
    path: "/teacher/schedules",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "معرفة مواعيد حصص المعلم خلال الأسبوع.",
    overview: "جدول أسبوعي شخصي — فقط الحصص المسندة لهذا المعلم.",
    elements: [
      {
        name: "جدول الحصص",
        type: "جدول",
        description: "أيام × حصص. كل خلية: الشعبة والمادة.",
      },
    ],
  }),
  page({
    id: "teacher-homework",
    section: "بوابة المعلم",
    title: "الواجبات",
    path: "/teacher/homework",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "إنشاء ومتابعة وتصحيح الواجبات المنزلية.",
    overview: "قائمة واجباتك مع فلاتر حسب الشعبة أو المادة. أزرار إضافة وتعديل وتصحيح.",
    elements: [
      {
        name: "زر «واجب جديد»",
        type: "زر",
        description: "ينقل إلى /teacher/homework/new لنموذج إنشاء واجب.",
      },
      {
        name: "بطاقة واجب",
        type: "بطاقة",
        description: "العنوان، الشعبة، موعد التسليم، عدد التسليمات.",
      },
      {
        name: "زر «تعديل»",
        type: "زر",
        description: "يفتح /teacher/homework/edit/[id].",
      },
      {
        name: "زر «تصحيح»",
        type: "زر",
        description: "يفتح قائمة تسليمات الطلاب /teacher/homework/[id]/grade.",
      },
    ],
    subPages: [
      { path: "/teacher/homework/new", title: "إنشاء واجب", description: "عنوان، وصف، مرفقات، شعبة، تاريخ تسليم." },
      { path: "/teacher/homework/edit/[id]", title: "تعديل واجب", description: "نفس الحقول مع بيانات محمّلة مسبقاً." },
      { path: "/teacher/homework/[id]/grade", title: "تصحيح واجب", description: "قائمة طلاب وتسليماتهم وإدخال الدرجة لكل طالب." },
    ],
  }),
  page({
    id: "teacher-homework-new",
    section: "بوابة المعلم",
    title: "إنشاء واجب جديد",
    path: "/teacher/homework/new",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "نشر تكليف جديد لطلاب شعبة محددة.",
    overview: "نموذج كامل لإنشاء الواجب.",
    elements: [
      { name: "حقل العنوان", type: "إدخال نص", description: "اسم مختصر للواجب يظهر لولي الأمر." },
      { name: "حقل الوصف", type: "منطقة نص", description: "تعليمات التكليف بالتفصيل." },
      { name: "اختيار الشعبة", type: "قائمة منسدلة", description: "الشعبة المستهدفة — من فصولك المسندة فقط." },
      { name: "تاريخ التسليم", type: "تاريخ", description: "آخر موعد لقبول التسليم." },
      { name: "رفع مرفق", type: "ملف", description: "PDF أو صور مساعدة للطلاب." },
      { name: "زر «حفظ» / «نشر»", type: "زر", description: "يرسل الواجب للخادم ويظهر فوراً لأولياء الأمور." },
    ],
  }),
  page({
    id: "teacher-quizzes",
    section: "بوابة المعلم",
    title: "الاختبارات",
    path: "/teacher/quizzes",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "إدارة الاختبارات الإلكترونية والتصحيح.",
    overview: "مشابهة لصفحة الواجبات لكن للاختبارات: إنشاء، أسئلة، تصحيح تلقائي أو يدوي.",
    elements: [
      { name: "زر «اختبار جديد»", type: "زر", description: "يفتح /teacher/quizzes/new." },
      { name: "بطاقة اختبار", type: "بطاقة", description: "العنوان، المادة، عدد الأسئلة، حالة النشر." },
      { name: "زر «تصحيح»", type: "زر", description: "مراجعة إجابات الطلاب وإعطاء الدرجات." },
    ],
    subPages: [
      { path: "/teacher/quizzes/new", title: "اختبار جديد", description: "إعداد الاختبار وإضافة أسئلة." },
      { path: "/teacher/quizzes/edit/[id]", title: "تعديل اختبار", description: "تعديل الأسئلة والإعدادات." },
      { path: "/teacher/quizzes/[id]/grade", title: "تصحيح اختبار", description: "قائمة تسليمات ودرجات." },
    ],
  }),
  page({
    id: "teacher-grade-entry",
    section: "بوابة المعلم",
    title: "إضافة التقييمات والعلامات",
    path: "/teacher/grade-entry",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "إدخال درجات الطلاب في بنود التقييم المعتمدة.",
    overview: "اختيار شعبة ومادة ثم جدول بأسماء الطلاب وأعمدة لكل بند (امتحان، مشاركة…).",
    elements: [
      { name: "فلتر الشعبة", type: "قائمة", description: "يحدد أي فصل تعمل عليه." },
      { name: "فلتر المادة", type: "قائمة", description: "المادة التي تدخل علاماتها." },
      { name: "خلايا إدخال الدرجة", type: "إدخال رقم", description: "كل خلية لطالب وبند. تُحفظ عند الخروج من الحقل أو زر حفظ جماعي." },
      { name: "زر «حفظ العلامات»", type: "زر", description: "يرسل كل التعديلات للخادم دفعة واحدة." },
    ],
  }),
  page({
    id: "teacher-announcements",
    section: "بوابة المعلم",
    title: "الإعلانات",
    path: "/teacher/announcements",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "نشر إعلانات لأولياء أمور شعبك.",
    overview: "قائمة إعلانات مع إمكانية إنشاء وتعديل.",
    elements: [
      { name: "زر «إعلان جديد»", type: "زر", description: "يفتح /teacher/announcements/new." },
      { name: "بطاقة إعلان", type: "بطاقة", description: "العنوان، التاريخ، الشعبة المستهدفة." },
      { name: "زر تعديل / حذف", type: "أزرار", description: "إدارة الإعلان المنشور." },
    ],
  }),
  page({
    id: "teacher-materials",
    section: "بوابة المعلم",
    title: "مرفقات المواد",
    path: "/teacher/materials",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "رفع ملفات تعليمية دائمة (مناهج، ملخصات) لكل مادة.",
    overview: "مكتبة ملفات مرتبطة بالمواد والشعب.",
    elements: [
      { name: "زر «مرفق جديد»", type: "زر", description: "يفتح /teacher/materials/new." },
      { name: "بطاقة ملف", type: "بطاقة", description: "اسم الملف، المادة، تاريخ الرفع." },
    ],
  }),
  page({
    id: "teacher-archive",
    section: "بوابة المعلم",
    title: "أرشيف السنوات السابقة",
    path: "/teacher/archive",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "مراجعة سجلات سنوات دراسية منتهية.",
    overview: "اختيار سنة ثم عرض واجبات وعلامات أرشيفية للقراءة.",
    elements: [
      { name: "قائمة السنة", type: "قائمة منسدلة", description: "السنة الدراسية المنتهية." },
      { name: "محتوى الأرشيف", type: "بطاقات", description: "ملخص بيانات تلك السنة." },
    ],
  }),
  page({
    id: "teacher-profile",
    section: "بوابة المعلم",
    title: "سيرتي الذاتية",
    path: "/teacher/profile",
    auth: AUTH.teacher,
    audience: AUDIENCE.teacher,
    purpose: "تحديث الملف العلني للمعلم على الموقع.",
    overview: "صورة، السيرة، المؤهلات — ما يظهر في صفحة الكادر العامة.",
    elements: [
      { name: "رفع صورة", type: "ملف", description: "صورة شخصية للملف العلني." },
      { name: "حقل السيرة", type: "منطقة نص", description: "نبذة عنك تظهر للزوار." },
      { name: "زر «حفظ»", type: "زر", description: "يحدّث ملفك على الخادم." },
    ],
  }),
];
