import { AUDIENCE, AUTH, page } from "./helpers.mjs";

const sideNav = (label) => ({
  name: `«${label}» في قائمة الإدارة`,
  type: "رابط تنقل",
  description: `ينقلك إلى ${label}. بعض الأدوار الفرعية قد لا ترى كل الروابط — المدير الكامل يرى الكل.`,
});

const periodBanner = {
  name: "شريط السنة والفصل الدراسي",
  type: "بانر",
  description: "يعرض الفترة الدراسية النشطة على لوحة الإدارة.",
};

export const adminPages = [
  page({
    id: "admin-home",
    section: "لوحة الإدارة",
    title: "الرئيسية",
    path: "/admin",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "نظرة عامة سريعة على أهم مؤشرات المدرسة.",
    overview: "بطاقات إحصائية: عدد الطلاب، المعلمين، طلبات معلقة، تنبيهات… مع روابط سريعة للأقسام.",
    elements: [sideNav("الرئيسية"), periodBanner, { name: "بطاقات KPI", type: "بطاقات", description: "أرقام ملوّنة مع أيقونات. بعضها قابل للنقر." }],
  }),
  page({
    id: "admin-analytics",
    section: "لوحة الإدارة",
    title: "التحليلات",
    path: "/admin/analytics",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "رسوم وتحليلات العلامات والتحصيل المالي.",
    overview: "تبويبان: نسب النجاح والعلامات، والتحصيل المالي. رسوم بيانية وجداول.",
    elements: [
      { name: "تبويب «العلامات»", type: "تبويب", description: "تحليل أداء الطلاب حسب الصف والمادة." },
      { name: "تبويب «المالية»", type: "تبويب", description: "معدلات التحصيل والمتأخرات." },
      { name: "فلاتر السنة/الصف", type: "قوائم", description: "تضييق نطاق التحليل." },
    ],
  }),
  page({
    id: "admin-notifications",
    section: "لوحة الإدارة",
    title: "التنبيهات",
    path: "/admin/notifications",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "متابعة تنبيهات النظام (رسوم متأخرة، طلبات جديدة…).",
    overview: "قائمة تنبيهات بتاريخ ونوع وزر إجراء.",
    elements: [
      { name: "بطاقة تنبيه", type: "بطاقة", description: "وصف المشكلة ورابط للصفحة المعنية." },
      { name: "زر «تمت المعالجة»", type: "زر", description: "يؤرشف التنبيه بعد الحل." },
    ],
  }),
  page({
    id: "admin-students",
    section: "لوحة الإدارة",
    title: "الطلاب",
    path: "/admin/students",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إدارة سجل الطلاب المسجّلين.",
    overview: "جدول بحث وفلترة. كل طالب: اسم، رقم، شعبة، ولي أمر. الضغط يفتح الملف.",
    elements: [
      { name: "حقل البحث", type: "بحث", description: "بالاسم أو الرقم." },
      { name: "زر «إضافة طالب»", type: "زر", description: "نموذج تسجيل طالب جديد." },
      { name: "صف طالب", type: "صف جدول", description: "يفتح /admin/students/[id]." },
    ],
    subPages: [
      { path: "/admin/students/[id]", title: "ملف طالب", description: "بيانات شخصية، شعبة، ولي أمر، أزرار تعديل." },
      { path: "/admin/students/[id]/documents", title: "وثائق الطالب", description: "رفع وعرض مستندات رسمية." },
    ],
  }),
  page({
    id: "admin-admissions",
    section: "لوحة الإدارة",
    title: "طلبات التسجيل",
    path: "/admin/admissions",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "مراجعة طلبات التسجيل من الموقع العام.",
    overview: "قائمة طلبات بحالة (جديد / مقبول / مرفوض). أزرار قبول ورفض.",
    elements: [
      { name: "بطاقة طلب", type: "بطاقة", description: "بيانات الطفل وولي الأمر من نموذج /register." },
      { name: "زر «قبول»", type: "زر أخضر", description: "يبدأ إجراءات تسجيل الطالب رسمياً." },
      { name: "زر «رفض»", type: "زر", description: "يرفض الطلب مع إمكانية ملاحظة." },
    ],
  }),
  page({
    id: "admin-classes",
    section: "لوحة الإدارة",
    title: "المراحل الدراسية",
    path: "/admin/classes",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "تعريف الصفوف والشعب (الفصول).",
    overview: "قائمة شعب: اسم، مرحلة، عدد طلاب. إضافة وتعديل.",
    elements: [
      { name: "زر «شعبة جديدة»", type: "زر", description: "إنشاء صف-شعبة جديدة." },
      { name: "حقل اسم الشعبة", type: "إدخال", description: "مثل: الصف الثاني - ب." },
    ],
  }),
  page({
    id: "admin-academic-years",
    section: "الإدارة الأكاديمية",
    title: "السنوات الدراسية",
    path: "/admin/academic-years",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إنشاء وتفعيل السنوات الدراسية يدوياً.",
    overview: "بعد نهاية السنة لا تُنشأ سنة جديدة تلقائياً — الإدارة تنشئها هنا وتفعّلها.",
    elements: [
      { name: "زر «سنة جديدة»", type: "زر", description: "اسم السنة (2027/2028) وتواريخ البداية والنهاية." },
      { name: "زر «تفعيل»", type: "زر", description: "يجعل السنة هي النشطة — سنة واحدة فقط نشطة." },
      { name: "شارة «نشطة»", type: "شارة", description: "تظهر بجانب السنة الحالية." },
    ],
  }),
  page({
    id: "admin-academic-terms",
    section: "الإدارة الأكاديمية",
    title: "الفصول الدراسية",
    path: "/admin/academic-terms",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "تعريف الفصل الأول والثاني لكل سنة مع تواريخ البداية والنهاية.",
    overview: "فصلان لكل سنة. الفصل النشط يحدد ما يظهر في البوابات.",
    elements: [
      { name: "حقل تاريخ البداية/النهاية", type: "تاريخ", description: "يحدد مدة الفصل." },
      { name: "زر تفعيل الفصل", type: "زر", description: "يجعل هذا الفصل هو الحالي." },
    ],
  }),
  page({
    id: "admin-promotion-policies",
    section: "الإدارة الأكاديمية",
    title: "سياسات الترفيع",
    path: "/admin/promotion-policies",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "قواعد النجاح والترفيع بين الصفوف.",
    overview: "حدود النجاح، إعادة السنة، شروط الترفيع التلقائي.",
    elements: [
      { name: "حقول النسب المئوية", type: "أرقام", description: "الحد الأدنى للنجاح والتفوق." },
      { name: "زر «حفظ السياسة»", type: "زر", description: "تطبيق القواعد على عمليات نهاية السنة." },
    ],
  }),
  page({
    id: "admin-certificate-settings",
    section: "الإدارة الأكاديمية",
    title: "إعدادات الشهادات",
    path: "/admin/certificate-settings",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "تخصيص قوالب ونصوص الشهادات الرسمية.",
    overview: "شعار، توقيعات، نصوص ثابتة على شهادات PDF.",
    elements: [
      { name: "رفع شعار الشهادة", type: "ملف", description: "يظهر أعلى الشهادة المطبوعة." },
      { name: "حقول النصوص", type: "نص", description: "عبارات رسمية (مدير المدرسة، إلخ)." },
    ],
  }),
  page({
    id: "admin-term-end",
    section: "الإدارة الأكاديمية",
    title: "نهاية الفصل",
    path: "/admin/term-end",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إغلاق الفصل الحالي ونشر الشهادات وتفعيل الفصل التالي عند استحقاقه.",
    overview:
      "معالج خطوات: التحقق من العلامات → إغلاق الفصل → نشر الشهادات. الفصل التالي يُفعّل فوراً إذا تاريخ نهاية الأول = بداية الثاني، وإلا عند تاريخ بداية الثاني.",
    elements: [
      { name: "قائمة التحقق", type: "خطوات", description: "بنود يجب اكتمالها قبل الإغلاق." },
      { name: "زر «إنهاء الفصل»", type: "زر تحذيري", description: "عملية لا تراجع عنها بسهولة — يغلق الفصل وينشر الشهادات." },
      { name: "رسالة تفعيل الفصل التالي", type: "تنبيه", description: "توضح متى يُفعّل الفصل التالي حسب التواريخ." },
    ],
    tips: ["لا خيار جداول هنا — نقل الجداول من قسم «الجداول»."],
  }),
  page({
    id: "admin-year-end",
    section: "الإدارة الأكاديمية",
    title: "نهاية السنة",
    path: "/admin/year-end",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إنهاء السنة الدراسية: ترفيع، أرشفة، شهادات نهاية السنة والتقدير فقط.",
    overview:
      "لا تُنشأ سنة جديدة تلقائياً. تُنشر شهادة نهاية السنة وشهادة التقدير دون شهادة فصل أخير منفصلة.",
    elements: [
      { name: "ملخص الطلاب", type: "جدول", description: "من يُرفّع ومن يُعاد." },
      { name: "زر «تنفيذ نهاية السنة»", type: "زر", description: "ينفذ الترفيع والأرشفة ونشر الشهادات السنوية." },
    ],
  }),
  page({
    id: "admin-academic-archive",
    section: "الإدارة الأكاديمية",
    title: "أرشيف السنوات",
    path: "/admin/academic-archive",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "استعراض بيانات سنوات منتهية للإدارة.",
    overview: "اختيار سنة وعرض ملخصات أرشيفية.",
    elements: [{ name: "قائمة السنوات", type: "قائمة", description: "السنوات المغلقة." }],
  }),
  page({
    id: "admin-schedules",
    section: "لوحة الإدارة",
    title: "الجداول",
    path: "/admin/schedules",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "بناء جداول الحصص لكل شعبة في الفصل الحالي.",
    overview: "محرر جدول + لوحة نقل الجداول بين الفصول (نسخ أو إنشاء جديد عند بداية فصل).",
    elements: [
      { name: "اختيار الشعبة", type: "قائمة", description: "أي جدول تُحرّر." },
      { name: "خلايا الجدول", type: "قوائم", description: "كل حصة: مادة ومعلم." },
      { name: "لوحة نقل الجداول", type: "بانل", description: "عند فصل جديد: الاحتفاظ بنسخة أو إنشاء جداول فارغة." },
      { name: "زر «حفظ الجدول»", type: "زر", description: "يحفظ التعديلات للفصل الدراسي النشط فقط." },
    ],
  }),
  page({
    id: "admin-grade-schemes",
    section: "لوحة الإدارة",
    title: "تقسيمة العلامات",
    path: "/admin/grade-schemes",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "تعريف أوزان بنود التقييم (أعمال، امتحان نصف فصل…).",
    overview: "لكل مرحلة أو مادة: بنود ونسب مئوية يجب أن تجمع 100%.",
    elements: [
      { name: "بنود التقييم", type: "صفوف", description: "اسم البند ووزنه." },
      { name: "زر إضافة بند", type: "زر", description: "بند تقييم جديد." },
    ],
  }),
  page({
    id: "admin-subjects",
    section: "لوحة الإدارة",
    title: "المواد",
    path: "/admin/subjects",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "قائمة المواد الدراسية وربطها بالمراحل.",
    overview: "إضافة مواد وتعديل أسمائها.",
    elements: [
      { name: "حقل اسم المادة", type: "إدخال", description: "مثل: علوم، لغة عربية." },
      { name: "ربط بالصفوف", type: "اختيارات", description: "في أي مراحل تُدرّس." },
    ],
  }),
  page({
    id: "admin-finance",
    section: "لوحة الإدارة",
    title: "المالية",
    path: "/admin/finance",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إدارة رسوم الطلاب والأقساط والإشعارات.",
    overview: "جداول أرصدة، تسجيل دفعات، إرسال إشعارات لأولياء الأمور.",
    elements: [
      { name: "جدول الأرصدة", type: "جدول", description: "كل طالب ورصيده." },
      { name: "زر «تسجيل دفعة»", type: "زر", description: "تسجيل مبلغ مدفوع." },
      { name: "زر «إرسال إشعار»", type: "زر", description: "تذكير ولي الأمر برسوم." },
    ],
  }),
  page({
    id: "admin-content",
    section: "لوحة الإدارة",
    title: "المحتوى",
    path: "/admin/content",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إدارة الأخبار والبرامج المعروضة على الموقع العام.",
    overview: "قائمة مقالات مع إنشاء وتعديل.",
    elements: [
      { name: "زر «محتوى جديد»", type: "زر", description: "يفتح /admin/content/new." },
      { name: "زر تعديل", type: "زر", description: "يفتح /admin/content/[id]/edit." },
    ],
  }),
  page({
    id: "admin-messages",
    section: "لوحة الإدارة",
    title: "رسائل التواصل",
    path: "/admin/messages",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "قراءة رسائل نموذج «تواصل» من الزوار.",
    overview: "صندوق وارد: اسم المرسل، الموضوع، النص، تاريخ.",
    elements: [
      { name: "بطاقة رسالة", type: "بطاقة", description: "معاينة الرسالة." },
      { name: "زر «تمت القراءة»", type: "زر", description: "تأشير الرسالة كمقروءة." },
    ],
  }),
  page({
    id: "admin-site",
    section: "لوحة الإدارة",
    title: "إعدادات الموقع",
    path: "/admin/site",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إعدادات عامة: اسم المدرسة، تواصل، إحصائيات الصفحة الرئيسية.",
    overview: "نماذج متعددة لتحديث محتوى الموقع العام دون برمجة.",
    elements: [
      { name: "حقول معلومات المدرسة", type: "نصوص", description: "العنوان، الهاتف، البريد." },
      { name: "إحصائيات Hero", type: "أرقام", description: "أرقام قسم الإحصائيات في الرئيسية." },
      { name: "زر «حفظ»", type: "زر", description: "تطبيق التغييرات فوراً على الموقع." },
    ],
  }),
  page({
    id: "admin-teachers",
    section: "لوحة الإدارة",
    title: "الكادر",
    path: "/admin/teachers",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إدارة حسابات المعلمين وملفاتهم.",
    overview: "قائمة معلمين مع إضافة وتعديل وربط بالشعب.",
    elements: [
      { name: "زر «معلم جديد»", type: "زر", description: "يفتح /admin/teachers/new." },
      { name: "صف معلم", type: "صف", description: "يفتح /admin/teachers/[id]." },
    ],
  }),
  page({
    id: "admin-users",
    section: "لوحة الإدارة",
    title: "المستخدمون",
    path: "/admin/users",
    auth: AUTH.admin,
    audience: AUDIENCE.admin,
    purpose: "إدارة حسابات الإدارة الفرعية وصلاحياتهم.",
    overview: "إنشاء مستخدمين بأدوار: إدارة طلاب، أكاديمية، مالية، محتوى، كادر.",
    elements: [
      { name: "قائمة الدور", type: "قائمة", description: "يحدد ما يراه المستخدم في القائمة الجانبية." },
      { name: "حقل اسم المستخدم وكلمة المرور", type: "إدخال", description: "بيانات الدخول." },
      { name: "زر «إنشاء»", type: "زر", description: "يحفظ المستخدم الجديد." },
    ],
  }),
];
